version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sisjur_db
    environment:
      POSTGRES_DB: sisjur_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - sisjur_data:/var/lib/postgresql/data

volumes:
  sisjur_data:
