
    create table advogados (
       id int8 generated by default as identity,
        email varchar(100) not null,
        nome varchar(150) not null,
        oab varchar(20) not null,
        telefone varchar(20),
        primary key (id)
    );

    alter table if exists advogados 
       add constraint UK_jd0yl6epmb89235m58n6ha8ho unique (email);

    alter table if exists advogados 
       add constraint UK_cp0ikk039sialao6balwn9ive unique (oab);

    create table advogados (
       id int8 generated by default as identity,
        cpf varchar(14) not null,
        email varchar(100) not null,
        nome varchar(150) not null,
        telefone varchar(20),
        oab varchar(20) not null,
        primary key (id)
    );

    alter table if exists advogados 
       add constraint UK_f8wa7737pl42tnr7uhef5nf3i unique (cpf);

    alter table if exists advogados 
       add constraint UK_jd0yl6epmb89235m58n6ha8ho unique (email);

    alter table if exists advogados 
       add constraint UK_cp0ikk039sialao6balwn9ive unique (oab);
